# Generated by Django 2.1.1 on 2019-09-23 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temp_library',
            options={'ordering': ('main_id', 'l_type'), 'verbose_name': '3-Test Setting', 'verbose_name_plural': '3-Test Settings'},
        ),
        migrations.AlterModelOptions(
            name='temp_pers_keywords',
            options={'ordering': ('main_id', 'standard_id', 'pers_id'), 'verbose_name': '5-Keyword Link Chain', 'verbose_name_plural': '5-Keywords Link Chain'},
        ),
        migrations.AlterModelOptions(
            name='temp_test_keywords',
            options={'ordering': ('my_order', 'main_id', 'test_id', 'key_id'), 'verbose_name': '4-Test Case Main Chain', 'verbose_name_plural': '4-Test Cases Main Chain'},
        ),
        migrations.AlterModelOptions(
            name='temp_variables',
            options={'ordering': ('main_id', 'v_key'), 'verbose_name': '2-Test Variable', 'verbose_name_plural': '2-Test Variables'},
        ),
        migrations.AddField(
            model_name='temp_test_keywords',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temp_case',
            name='main_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tm_tc', to='backend.temp_main', verbose_name='Main Template'),
        ),
        migrations.AlterField(
            model_name='temp_test_keywords',
            name='key_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tk_ttk', to='backend.temp_keywords', verbose_name='Keyword'),
        ),
        migrations.AlterField(
            model_name='temp_test_keywords',
            name='main_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tm_ttk', to='backend.temp_main', verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='temp_test_keywords',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tc_ttk', to='backend.temp_case', verbose_name='Test Case'),
        ),
    ]
