# Generated by Django 2.1.1 on 2019-09-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190923_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temp_test_keywords',
            options={'ordering': ['my_order'], 'verbose_name': '4-Test Case Main Chain', 'verbose_name_plural': '4-Test Cases Main Chain'},
        ),
    ]
