# Generated by Django 2.1.1 on 2019-09-26 12:44

import backend.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190925_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='suite_libs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('descr', models.TextField(blank=True, null=True)),
                ('docs', models.TextField(blank=True, editable=False, null=True)),
                ('lib_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='PENDING', editable=False, max_length=10)),
                ('f_lib', models.FileField(blank=True, upload_to='libs/', validators=[django.core.validators.FileExtensionValidator(['py']), backend.models.validate_fsize], verbose_name='File ( .py Max 150Kb )')),
                ('notes', models.TextField(blank=True, null=True)),
                ('dt', models.DateTimeField(auto_now=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'LIBRARIES',
                'verbose_name_plural': 'LIBRARIES',
                'ordering': ('name', 'lib_name', 'status'),
            },
        ),
        migrations.AlterField(
            model_name='temp_library',
            name='l_val',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='li_val', to='backend.suite_libs', verbose_name='Library'),
        ),
    ]
