# Generated by Django 2.1.1 on 2019-09-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190926_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_library',
            name='l_val',
            field=models.CharField(max_length=100, verbose_name='Value'),
        ),
    ]
