# Generated by Django 2.1.1 on 2019-09-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20190926_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_library',
            name='l_val',
            field=models.CharField(max_length=254, verbose_name='Value'),
        ),
    ]
