# Generated by Django 2.1.1 on 2019-09-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20190926_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_test_keywords',
            name='key_val',
            field=models.TextField(blank=True, null=True, verbose_name='Value'),
        ),
    ]
