# Generated by Django 2.1.1 on 2019-09-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20190926_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_main',
            name='descr',
            field=models.CharField(max_length=200, unique=True, verbose_name='Description'),
        ),
    ]
