# Generated by Django 2.1.1 on 2019-09-26 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20190926_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_library',
            name='l_type',
        ),
        migrations.AlterField(
            model_name='temp_library',
            name='l_val',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='li_val', to='backend.suite_libs', verbose_name='Library'),
        ),
    ]
