# Generated by Django 2.1.1 on 2019-09-26 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20190926_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temp_library',
            options={'ordering': ('main_id', 'l_val'), 'verbose_name': '3-Test Library', 'verbose_name_plural': '3-Test Libraries'},
        ),
    ]
