# Generated by Django 2.1.1 on 2019-09-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20190927_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suite_libs',
            name='docs',
            field=models.TextField(blank=True, null=True, verbose_name='Doc Link'),
        ),
        migrations.AlterField(
            model_name='suite_libs',
            name='lib_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Import Name'),
        ),
    ]
