# Generated by Django 2.1.1 on 2019-09-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20190927_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suite_libs',
            name='docs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Doc Link'),
        ),
    ]
