# Generated by Django 2.1.1 on 2019-09-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20190927_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suite_libs',
            name='lib_name',
            field=models.CharField(max_length=255, verbose_name='Import Name'),
        ),
        migrations.AlterField(
            model_name='suite_libs',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
