# Generated by Django 2.1.1 on 2019-09-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20190927_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_main',
            name='t_resfile',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Resource file'),
        ),
        migrations.AddField(
            model_name='temp_main',
            name='t_varfile',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Variables file'),
        ),
    ]
