# Generated by Django 2.1.1 on 2019-09-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20190927_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temp_test_keywords',
            options={'ordering': ('my_order',), 'verbose_name': '4-Test Case Main Chain', 'verbose_name_plural': '4-Test Cases Main Chain'},
        ),
        migrations.AlterField(
            model_name='temp_test_keywords',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Drag to reorder'),
        ),
    ]
