# Generated by Django 2.1.1 on 2019-09-28 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20190927_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temp_pers_keywords',
            options={'ordering': ('my_order',), 'verbose_name': '5-Keyword Link Chain', 'verbose_name_plural': '5-Keywords Link Chain'},
        ),
        migrations.RemoveField(
            model_name='temp_pers_keywords',
            name='pers_id',
        ),
        migrations.RemoveField(
            model_name='temp_pers_keywords',
            name='standard_id',
        ),
        migrations.RemoveField(
            model_name='temp_pers_keywords',
            name='variable_val',
        ),
        migrations.AddField(
            model_name='temp_pers_keywords',
            name='key_descr',
            field=models.CharField(default='NoDAta', max_length=200, unique=True, verbose_name='Key Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_pers_keywords',
            name='key_group',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='temp_pers_keywords',
            name='key_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tk_tpk', to='backend.temp_keywords', verbose_name='Keyword'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_pers_keywords',
            name='key_val',
            field=models.TextField(blank=True, null=True, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='temp_pers_keywords',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Drag to reorder'),
        ),
    ]
