# Generated by Django 2.1.1 on 2019-09-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20190928_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_pers_keywords',
            name='key_descr',
            field=models.CharField(max_length=200, verbose_name='Key Name'),
        ),
    ]
