# Generated by Django 2.1.1 on 2019-09-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20190928_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_keywords',
            name='personal',
        ),
    ]
