# Generated by Django 2.1.1 on 2019-09-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_remove_temp_keywords_personal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temp_pers_keywords',
            options={'ordering': ('my_order',), 'verbose_name': 'PERSONAL KEYWORDS', 'verbose_name_plural': 'PERSONAL KEYWORDS'},
        ),
    ]
