# Generated by Django 2.1.1 on 2019-10-08 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_auto_20190928_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temp_variables',
            options={'verbose_name': '2-Test Variable', 'verbose_name_plural': '2-Test Variables'},
        ),
    ]
