# Generated by Django 2.1.1 on 2019-10-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_auto_20191008_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_library',
            name='l_param',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Parameter'),
        ),
    ]
