# Generated by Django 2.1.1 on 2019-10-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_temp_library_l_param'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temp_library',
            options={'verbose_name': '3-Test Library', 'verbose_name_plural': '3-Test Libraries'},
        ),
    ]
