# Generated by Django 2.1.1 on 2019-10-08 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_auto_20191008_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temp_library',
            options={'verbose_name': '2-Test Library', 'verbose_name_plural': '2-Test Libraries'},
        ),
        migrations.AlterModelOptions(
            name='temp_variables',
            options={'verbose_name': '3-Test Variable', 'verbose_name_plural': '3-Test Variables'},
        ),
    ]
