# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-14 06:18
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20181113_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='on_trial',
        ),
        migrations.RemoveField(
            model_name='client',
            name='paid_feed',
        ),
        migrations.AddField(
            model_name='settings_gen',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='2018-11-14 11:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings_gen',
            name='on_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings_gen',
            name='paid_feed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
