# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-22 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20181120_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings_gen',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
