version: '3'

networks:
  mynetwork:
    driver: bridge

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 11235813post
      POSTGRES_DB: cath_local
    volumes:
      - ./data:/var/lib/postgresql/data

  web:
    build: .
    networks:
      - mynetwork

    volumes:
      - .:/code

    ports:
      - "8000:8000"

    depends_on:
      - db