# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 13:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='t_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=200)),
                ('exec_data', models.DateTimeField(auto_now=True)),
                ('exec_status', models.CharField(max_length=10)),
                ('exec_result', models.BinaryField()),
                ('quick_res', models.IntegerField(default=0)),
                ('exec_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='t_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_data', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('num_exec', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='t_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=30)),
                ('test_data', models.BinaryField()),
                ('test_creation', models.DateTimeField(auto_now=True)),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='t_schedule',
            name='id_test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frontend.t_test'),
        ),
        migrations.AddField(
            model_name='t_history',
            name='id_test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frontend.t_test'),
        ),
    ]
