# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='temp_keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=200, unique=True)),
                ('human', models.CharField(max_length=200, unique=True)),
                ('personal', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='temp_library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_type', models.CharField(max_length=50)),
                ('l_val', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='temp_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=200)),
                ('dt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='temp_pers_keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.temp_main')),
                ('pers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_key', to='frontend.temp_keywords')),
                ('standard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_key', to='frontend.temp_keywords')),
            ],
        ),
        migrations.CreateModel(
            name='temp_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_type', models.CharField(max_length=50, unique=True)),
                ('s_lib', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='temp_variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_key', models.CharField(max_length=200)),
                ('v_val', models.CharField(max_length=200)),
                ('main_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.temp_main')),
            ],
        ),
        migrations.RemoveField(
            model_name='t_test',
            name='id_user',
        ),
        migrations.AddField(
            model_name='t_test',
            name='ip_addr',
            field=models.CharField(default='ciao', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_pers_keywords',
            name='variable_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.temp_variables'),
        ),
        migrations.AddField(
            model_name='temp_library',
            name='main_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.temp_main'),
        ),
        migrations.AddField(
            model_name='temp_case',
            name='main_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frontend.temp_main'),
        ),
    ]
