# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20170609_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_pers_keywords',
            name='pers_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_key', to='frontend.temp_keywords'),
        ),
    ]
