# Generated by Django 2.1.1 on 2018-09-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20180925_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_group',
            options={'ordering': ('descr',), 'verbose_name': 'TEST GROUP MANAGER', 'verbose_name_plural': 'TEST GROUP MANAGER'},
        ),
        migrations.AlterModelOptions(
            name='t_group_test',
            options={'ordering': ('temp_ord',), 'verbose_name': 'TEST GROUP ITEMS', 'verbose_name_plural': 'TEST GROUP ITEMS'},
        ),
    ]
