# Generated by Django 2.1.1 on 2018-09-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20180925_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='settings_gen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
