# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20170609_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_pers_keywords',
            name='variable_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.temp_variables'),
        ),
    ]
