# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-20 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20181114_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill_his',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_data', models.DateTimeField()),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_errors', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='settings_gen',
            name='addr_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='settings_gen',
            name='addr_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='settings_gen',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='settings_gen',
            name='comp_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='settings_gen',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings_gen',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings_gen',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings_gen',
            name='paid_plan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='settings_gen',
            name='postal_zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='settings_gen',
            name='state_prov',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings_gen',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_time',
            name='stop_data',
            field=models.DateTimeField(blank=True, default='2018-11-20 11:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='domain_url',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='client',
            name='schema_name',
            field=models.CharField(blank=True, max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='t_time',
            name='history_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.t_history', verbose_name='History'),
        ),
    ]
