# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_delete_temp_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_test_keywords',
            name='variable_id',
        ),
        migrations.AddField(
            model_name='temp_test_keywords',
            name='key_val',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
