# Generated by Django 2.1.1 on 2019-09-06 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20190521_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp_case',
            name='main_id',
        ),
        migrations.RemoveField(
            model_name='temp_case',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='temp_keywords',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='temp_library',
            name='main_id',
        ),
        migrations.RemoveField(
            model_name='temp_library',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='temp_main',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='temp_pers_keywords',
            name='main_id',
        ),
        migrations.RemoveField(
            model_name='temp_pers_keywords',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='temp_pers_keywords',
            name='pers_id',
        ),
        migrations.RemoveField(
            model_name='temp_pers_keywords',
            name='standard_id',
        ),
        migrations.RemoveField(
            model_name='temp_test_keywords',
            name='key_id',
        ),
        migrations.RemoveField(
            model_name='temp_test_keywords',
            name='main_id',
        ),
        migrations.RemoveField(
            model_name='temp_test_keywords',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='temp_test_keywords',
            name='test_id',
        ),
        migrations.RemoveField(
            model_name='temp_variables',
            name='main_id',
        ),
        migrations.RemoveField(
            model_name='temp_variables',
            name='owner',
        ),
        migrations.AddField(
            model_name='settings_gen',
            name='lic_num',
            field=models.CharField(blank=True, max_length=255, verbose_name='License Number'),
        ),
        migrations.AlterField(
            model_name='t_group_test',
            name='id_temp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.temp_main', verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='t_history',
            name='test_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.temp_main'),
        ),
        migrations.AlterField(
            model_name='t_proj_route',
            name='main_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.temp_main'),
        ),
        migrations.AlterField(
            model_name='t_tags_route',
            name='main_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.temp_main'),
        ),
        migrations.DeleteModel(
            name='temp_case',
        ),
        migrations.DeleteModel(
            name='temp_keywords',
        ),
        migrations.DeleteModel(
            name='temp_library',
        ),
        migrations.DeleteModel(
            name='temp_main',
        ),
        migrations.DeleteModel(
            name='temp_pers_keywords',
        ),
        migrations.DeleteModel(
            name='temp_test_keywords',
        ),
        migrations.DeleteModel(
            name='temp_variables',
        ),
    ]
