# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20170614_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_case',
            name='main_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.temp_main'),
        ),
    ]
