# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20170616_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_test',
            name='test_html',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_test',
            name='test_rst',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temp_case',
            name='descr',
            field=models.CharField(max_length=200),
        ),
    ]
