# Generated by Django 2.1.1 on 2019-09-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20190906_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_gen',
            name='lic_num',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='License Number'),
        ),
        migrations.AlterField(
            model_name='settings_gen',
            name='tenant_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='System Name'),
        ),
    ]
