# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20170619_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_history',
            old_name='exec_result',
            new_name='xml_result',
        ),
        migrations.RemoveField(
            model_name='t_history',
            name='id_test',
        ),
        migrations.RemoveField(
            model_name='t_history',
            name='quick_res',
        ),
        migrations.RemoveField(
            model_name='t_history',
            name='target',
        ),
        migrations.AddField(
            model_name='t_history',
            name='html_test',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_history',
            name='id_main',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.temp_main'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_history',
            name='var_test',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
