# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20170623_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_history',
            name='xml_result',
            field=models.TextField(),
        ),
    ]
