# Generated by Django 2.1.1 on 2019-09-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20190906_1132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='suite_libs',
        ),
    ]
