# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 06:04
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_auto_20170623_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_main', models.IntegerField(default=0)),
                ('elapsed_t', models.DecimalField(decimal_places=6, default=Decimal('0.0000'), max_digits=20)),
            ],
        ),
        migrations.AddField(
            model_name='t_history',
            name='pid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
