# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_auto_20170624_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_time',
            old_name='test_main',
            new_name='history_main',
        ),
    ]
