# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_auto_20170624_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_schedule',
            name='num_exec',
        ),
        migrations.RemoveField(
            model_name='t_schedule',
            name='start_data',
        ),
        migrations.RemoveField(
            model_name='t_schedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='t_schedule',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='t_schedule',
            name='exec_at',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_schedule',
            name='exec_every',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_schedule',
            name='exec_main',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_schedule',
            name='last_exec',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='t_schedule',
            name='plan_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
