# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_auto_20170628_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_schedsettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sched_desc', models.CharField(max_length=20)),
                ('sched_command', models.CharField(max_length=20)),
                ('sched_note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
