# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_t_history_thread_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_threads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(blank=True, max_length=50, null=True)),
                ('thread_main', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='t_history',
            name='thread_id',
        ),
        migrations.RemoveField(
            model_name='t_history',
            name='thread_main',
        ),
        migrations.AddField(
            model_name='t_threads',
            name='id_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.t_history'),
        ),
    ]
