# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_auto_20170703_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_threads',
            name='thread_stag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='t_threads',
            name='thread_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
