# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_t_threads_thread_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_threads',
            name='thread_startd',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='t_threads',
            name='thread_stopd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
