# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_auto_20170706_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_threads',
            name='thread_alive',
        ),
    ]
