# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_auto_20170706_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=50)),
                ('g_prior', models.IntegerField(default=1)),
                ('g_desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_group_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_ord', models.IntegerField(default=0)),
                ('id_grp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.t_group')),
                ('id_temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.temp_main')),
            ],
        ),
    ]
