# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_t_group_t_group_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_group',
            old_name='g_name',
            new_name='descr',
        ),
    ]
