# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 04:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0026_auto_20170712_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_history',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.t_group'),
        ),
        migrations.AddField(
            model_name='t_history',
            name='user_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
