# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0028_remove_t_history_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_history',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.t_group'),
        ),
    ]
