# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0029_t_history_group_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temp_case',
            options={'verbose_name': '2-Test Case', 'verbose_name_plural': '2-Test Cases'},
        ),
        migrations.AlterModelOptions(
            name='temp_keywords',
            options={'verbose_name': '3-Test Keyword', 'verbose_name_plural': '3-Test Keywords'},
        ),
        migrations.AlterModelOptions(
            name='temp_library',
            options={'verbose_name': '5-Test Library', 'verbose_name_plural': '5-Test Libraries'},
        ),
        migrations.AlterModelOptions(
            name='temp_main',
            options={'verbose_name': '1-Main Template', 'verbose_name_plural': '1-Main Templates'},
        ),
        migrations.AlterModelOptions(
            name='temp_pers_keywords',
            options={'verbose_name': 'Keyword Link Chain', 'verbose_name_plural': 'Keywords Link Chain'},
        ),
        migrations.AlterModelOptions(
            name='temp_test_keywords',
            options={'verbose_name': 'Test Case Main Chain', 'verbose_name_plural': 'Test Cases Main Chain'},
        ),
        migrations.AlterModelOptions(
            name='temp_variables',
            options={'verbose_name': '4-Test Variable', 'verbose_name_plural': '4-Test Variables'},
        ),
        migrations.AddField(
            model_name='temp_main',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temp_case',
            name='descr',
            field=models.CharField(max_length=200, verbose_name='Case description'),
        ),
    ]
