# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0030_auto_20170817_0732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temp_case',
            options={'ordering': ('descr',), 'verbose_name': '2-Test Case', 'verbose_name_plural': '2-Test Cases'},
        ),
        migrations.AlterModelOptions(
            name='temp_keywords',
            options={'ordering': ('descr',), 'verbose_name': '3-Test Keyword', 'verbose_name_plural': '3-Test Keywords'},
        ),
        migrations.AlterModelOptions(
            name='temp_library',
            options={'ordering': ('main_id', 'l_type'), 'verbose_name': '5-Test Library', 'verbose_name_plural': '5-Test Libraries'},
        ),
        migrations.AlterModelOptions(
            name='temp_pers_keywords',
            options={'ordering': ('main_id', 'standard_id', 'pers_id'), 'verbose_name': 'Keyword Link Chain', 'verbose_name_plural': 'Keywords Link Chain'},
        ),
        migrations.AlterModelOptions(
            name='temp_test_keywords',
            options={'ordering': ('main_id', 'test_id', 'key_id'), 'verbose_name': 'Test Case Main Chain', 'verbose_name_plural': 'Test Cases Main Chain'},
        ),
        migrations.AlterModelOptions(
            name='temp_variables',
            options={'ordering': ('main_id', 'v_key'), 'verbose_name': '4-Test Variable', 'verbose_name_plural': '4-Test Variables'},
        ),
        migrations.AlterField(
            model_name='temp_case',
            name='main_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.temp_main', verbose_name='Main Template'),
        ),
        migrations.AlterField(
            model_name='temp_main',
            name='descr',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='temp_main',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
