# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-18 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0031_auto_20170817_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_variables',
            name='v_val',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
