# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0032_auto_20170818_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temp_keywords',
            options={'ordering': ('descr',), 'verbose_name': 'KEYWORD', 'verbose_name_plural': 'KEYWORDS'},
        ),
        migrations.AlterModelOptions(
            name='temp_library',
            options={'ordering': ('main_id', 'l_type'), 'verbose_name': '4-Test Setting', 'verbose_name_plural': '4-Test Settings'},
        ),
        migrations.AlterModelOptions(
            name='temp_pers_keywords',
            options={'ordering': ('main_id', 'standard_id', 'pers_id'), 'verbose_name': '6-Keyword Link Chain', 'verbose_name_plural': '6-Keywords Link Chain'},
        ),
        migrations.AlterModelOptions(
            name='temp_test_keywords',
            options={'ordering': ('main_id', 'test_id', 'key_id'), 'verbose_name': '5-Test Case Main Chain', 'verbose_name_plural': '5-Test Cases Main Chain'},
        ),
        migrations.AlterModelOptions(
            name='temp_variables',
            options={'ordering': ('main_id', 'v_key'), 'verbose_name': '3-Test Variable', 'verbose_name_plural': '3-Test Variables'},
        ),
        migrations.AlterField(
            model_name='t_history',
            name='test_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.temp_main'),
        ),
    ]
