# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 21:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0034_auto_20170829_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_group',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='t_group',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
