# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0035_auto_20170919_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('tag_notes', models.TextField()),
            ],
            options={
                'ordering': ('tag',),
                'verbose_name': '7-Tags for Templates',
                'verbose_name_plural': '7-Tags for Templates',
            },
        ),
        migrations.CreateModel(
            name='t_tags_route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_notes', models.TextField()),
                ('main_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.temp_main')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.t_tags')),
            ],
            options={
                'ordering': ('main_id', 'tag_id', 'route_notes'),
                'verbose_name': '7-Tags for Templates',
                'verbose_name_plural': '7-Tags for Templates',
            },
        ),
    ]
