# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0036_t_tags_t_tags_route'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_tags',
            options={'ordering': ('descr',), 'verbose_name': 'TAGS', 'verbose_name_plural': 'TAGS'},
        ),
        migrations.RenameField(
            model_name='t_tags',
            old_name='tag',
            new_name='descr',
        ),
    ]
