# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0037_auto_20171211_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_tags',
            name='tag_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_tags_route',
            name='route_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
