# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-31 09:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0038_auto_20171211_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_test',
            name='highlighted',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_test',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='t_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_main',
            name='highlighted',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_main',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tmain_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
