# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-31 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0039_auto_20180131_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_test',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='temp_main',
            name='highlighted',
        ),
    ]
