# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 16:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0040_auto_20180131_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_group',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tgrp_owner', to=settings.AUTH_USER_MODEL, verbose_name='API Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_group_test',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tgrptest_owner', to=settings.AUTH_USER_MODEL, verbose_name='API Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_tags',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ttags_owner', to=settings.AUTH_USER_MODEL, verbose_name='API Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_tags_route',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ttagsroute_owner', to=settings.AUTH_USER_MODEL, verbose_name='API Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_case',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tcase_owner', to=settings.AUTH_USER_MODEL, verbose_name='API Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_keywords',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tkey_owner', to=settings.AUTH_USER_MODEL, verbose_name='API Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_library',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tlib_owner', to=settings.AUTH_USER_MODEL, verbose_name='API Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_pers_keywords',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tperskey_owner', to=settings.AUTH_USER_MODEL, verbose_name='API Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_test_keywords',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ttestkey_owner', to=settings.AUTH_USER_MODEL, verbose_name='API Owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temp_variables',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tvar_owner', to=settings.AUTH_USER_MODEL, verbose_name='API Owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temp_main',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tmain_owner', to=settings.AUTH_USER_MODEL, verbose_name='API Owner'),
        ),
    ]
