# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-16 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0043_auto_20180404_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_proj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=50)),
                ('proj_notes', models.TextField(blank=True, null=True)),
                ('proj_actors', models.TextField(blank=True, null=True)),
                ('proj_start', models.DateTimeField(auto_now=True, null=True)),
                ('proj_stop', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tproj_owner', to=settings.AUTH_USER_MODEL, verbose_name='API Owner')),
            ],
            options={
                'ordering': ('descr',),
                'verbose_name': 'PROJECTS',
                'verbose_name_plural': 'PROJECTS',
            },
        ),
        migrations.CreateModel(
            name='t_proj_route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_notes', models.TextField(blank=True, null=True)),
                ('main_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.temp_main')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tprojroute_owner', to=settings.AUTH_USER_MODEL, verbose_name='API Owner')),
                ('proj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.t_proj')),
            ],
            options={
                'ordering': ('main_id', 'proj_id', 'route_notes'),
                'verbose_name': '8-Projects Templates link',
                'verbose_name_plural': '8-Projects Templates link',
            },
        ),
    ]
