# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-30 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0047_auto_20180430_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='owner',
            field=models.IntegerField(default=0),
        ),
    ]
