# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-04 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0052_auto_20180604_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dmessage',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
