# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-07 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0053_document_dmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_test_keywords',
            name='key_group',
            field=models.IntegerField(default=0),
        ),
    ]
