# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-12 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0054_temp_test_keywords_key_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_test_keywords',
            name='key_group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
