# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-20 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0055_auto_20180612_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_history',
            name='test_group',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='t_history',
            name='test_type',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
