# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-21 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0056_auto_20180720_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_history',
            name='test_group',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
