# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-21 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0057_auto_20180721_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_history',
            name='sched_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='t_history',
            name='sched_val',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
