# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-21 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0058_auto_20180721_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_history',
            name='sched_val',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
