# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-23 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0059_auto_20180721_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_threads',
            name='thread_stype',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='t_threads',
            name='thread_sval',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='t_threads',
            name='thread_tgroup',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='t_threads',
            name='thread_ttype',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
