# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-23 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0060_auto_20180723_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_history',
            name='thread_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
